# Generated by Django 3.0.6 on 2020-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=200)),
                ('hero_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owhighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_potg', models.BooleanField(default=False)),
                ('hero_vid', models.CharField(max_length=200)),
                ('vid_url', models.URLField()),
            ],
        ),
    ]
